#!/Users/smcho/virtualenv/riki/bin/python

# -*- coding: utf-8 -*-
import re
import sys
import os

from wiki.web import create_app

directory = os.getcwd()
app = create_app(directory)

if __name__ == '__main__':
    app.run(host='0.0.0.0', debug=True)

    '''
if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(main())
    '''
